- csharp/private/toolchains.bzl
This restriction isn't particularly valid in the long run. You could consider trying to do it when building .NET Framework targets, but given you can use mono as a runtime, that still isn't particularly correct
> Remove target_compatible_with restriction

- csharp/private/common.bzl
This was a minor bug I noticed when building `//examples:lib_test`.
> Stop after the first compatible framework

- csharp/private/common.bzl
- csharp/private/rules/binary.bzl
- csharp/private/rules/nunit_test.bzl
This just makes sure we have a good error message if the user tries it.
Fixing this brought to light that we don't actually support .NET
Standard tests because we are producing an exe for Bazel to run. We
should still do that, but without modifying the users assembly (our shim
can link the tests in at runtime).
Fixes #5.
> Don't allow netstandard framworks for executables

- csharp/private/actions/assembly.bzl
- csharp/private/common.bzl
- csharp/private/providers.bzl
- csharp/private/rules/binary.bzl
- csharp/private/rules/imports.bzl
- csharp/private/rules/nunit_test.bzl
This goes towards #9, but doesn't fix it. We still need to deal with how
these files aren't all collected into a single directory.
> Add runfiles to binary outputs

- csharp/private/frameworks/netstandard20.BUILD
- csharp/private/net/BUILD
- csharp/private/repositories.bzl
So it turns out that all the `netstandard2.0` assemblies are type-forwarded to
`netstandard.dll`. That means our `BUILD` file for `netstandard2.0` can be
quite simple.
I verified that every DLL in `NetStandard.Library` already had a target  in
`@net` with this command:
```sh
ls $NetStandardLibrary/build/netstandard2.0/ref/*.dll \
| sed 's:\.dll$::' \
| xargs -n1 dash -c 'grep -q "name = \"$0\"" ~/rules_csharp/csharp/private/net/BUILD || echo $0'
```
Which prints out the name of missing targets, and I got no lines of output. I
generated a batch file for [buildozer](https://github.com/bazelbuild/buildtools/tree/master/buildozer) with this command:
```sh
ls $NetStandardLibrary/build/netstandard2.0/ref/*.dll \
| sed 's:.*/::' | sed 's:\.dll$::' \
| sed 's_^_set netstandard20 …
```
> Add netstandard2.0 to @net

- .bazelci/presubmit.yml
Related to #42 
I also need to submit an issue in their repo, according to [the documentation](https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md).
I've kept this pretty basic. We'd like to test on the 3 major platforms. There are some other things I'd like in the future:
- run & test targets: blocked on #9 
- buildifier linting: blocked on us formatting our code
- using remote builds (i.e. the `rbe_ubuntu1604` platform): this is probably blocked on as-of-yet-unfiled issue where we have a bit too many implicit dependencies on the exec environment (e.g. libicu) it's why we aren't doing `bazel build` inside our GitHub action (which runs in the "official" Bazel containers, which RBE may use...)
For the extra stuff that might not succeed on attempt 1 it'll be …
> Add .bazelci/presubmit.yml

- csharp/private/common.bzl
- csharp/private/providers.bzl
This is the easy part for #41.
The next step is to add csharp_library_set, which only has the deps
attribute. That's seems to be slightly non-trivial because our existing
helpers don't quite cut it.
The final piece of the puzzle is creating the @net//:StandardLibrary
target with a csharp_library_set that deps on @net48//:StandardLibrary
etc. That's easy but a bit tedious.
> Allow CSharpProviders to have neither out/refout

- csharp/private/rules/binary.bzl
- csharp/private/rules/library.bzl
- csharp/private/rules/nunit_test.bzl
- examples/diamond/BUILD
This is another incremental step towards #41.
The default value will be @net//:StandardLibrary eventually, and the
idea is that if you don't want this you can set the attr to be None
explicitly.
> Add a stdlib attribute to the compilation rules

- csharp/private/actions/assembly.bzl
- csharp/private/rules/binary.bzl
- csharp/private/rules/library.bzl
- csharp/private/rules/nunit_test.bzl
This decouples the name of the built assembly from the name of the
Bazel target. If not specified, the name of the target is used.
Fixes #73.
> Add 'out' attribute to assembly-building commands

- csharp/private/actions/assembly.bzl
- csharp/private/rules/binary.bzl
- csharp/private/rules/library.bzl
- csharp/private/rules/nunit_test.bzl
Allows the user to build a strong-named assembly by specifying
a label (can be a single file) to a key file.
> Adding strong-naming via /keyfile: compiler switch

- csharp/defs.bzl
- csharp/private/rules/library_set.bzl
used for collecting assemblies into groups
> add a csharp_library_set rule

- csharp/private/rules/library.bzl
This allows dependent rules to easily use `csharp_library` rules for
things like copying files to another output location. Having multiple
files returned makes such a thing difficult.
> Moving csharp_library to have a single file in returned DefaultInfo

- csharp/private/build-tools.BUILD
- csharp/private/repositories.bzl
- csharp/private/runtime.BUILD
- csharp/private/toolchains.bzl
ResX compilation works by creating a `.csproj` with the resx file as an embedded resource. When compiled (using GenerateResourceTask), it will create the `.resources` file that can then be embedded in the csharp lib/binary. To compile the csproj, we need the dotnet sdk.
Downloading the dotnet SDK on windows (`dotnet-sdk-windows`) takes around 86 seconds, and goes from ~45 MB (runtime + compiler) to ~110-150 MB (depending on OS).
Related to #10 and #96
> Replace dotnet runtime with SDK

- csharp/private/wrappers/dotnet.cc
Resolve inconsistent comment style in the dotnet wrapper (`dotnetw`).
> Use common comment style as per guidelines

- csharp/private/repositories.bzl
- csharp/private/runtime.BUILD
- csharp/private/sdk.bzl
- csharp/private/toolchains.bzl
Upgrade to the latest version of the DotNET SDK.
You can see the release notes [here](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.0/3.1.0.md) (download path [here](https://dotnet.microsoft.com/download/dotnet-core/3.1))
Additionally refactored the SDK URLs and version information into the file `sdk.bzl`, so in the future it is easier to upgrade this dependency.
> Upgrade the Dotnet SDK to 3.1.100 from 3.0.100

- .bazelci/presubmit.yml
Upgrade to the latest version of bazel in CI. This is related to the discussion in #101 about pinning vs. latest upgrading of the version of bazel.
There is a [fix](https://github.com/bazelbuild/bazel/commit/ceadf0a063cb97c32aced143d2447781d1dafc38) that may be of use in the development of ResX compilation, as that is using runfiles a lot for its compilation.
> Upgrade to latest bazel version in CI

- csharp/private/wrappers/dotnet.cc
The issue was an incorrect array size for the copied arguments. The array was set to size `argc`, but then an element outside of those bounds was being setting `nullptr`.
Tested by running the code over and over and over:
```bash
for i in {1..15}; do bazel clean && bazel build ///resgen:hello; done
```
Resolves #107 
I'll sum up my emotions as such:
> Resolve segmentation error with dotnet wrapper

- csharp/private/BUILD
- csharp/private/actions/assembly.bzl
- csharp/private/common.bzl
- csharp/private/macros/setup_basic_nuget_package.bzl
- csharp/private/net/BUILD
- csharp/private/providers.bzl
- csharp/private/rules/create_net_workspace.bzl
- csharp/private/rules/imports.bzl
- csharp/private/rules/library_set.bzl
- csharp/private/rules/wrapper.bzl
- csharp/private/sdk.bzl
- csharp/private/toolchains.bzl
- examples/diamond/BUILD
- examples/every_framework_empty/BUILD
- examples/import_nuget_package/BUILD
While raising some of my recent pull requests, I have been noticing that there are some files that I keep re-formatting. I'd prefer to get all of these sorted, rather than format the files one-by-one.
This PR runs `buildifier -r .` on the entire codebase, ensuring that everything is following the standard set by `buildifier`.
We should look at potentially enforcing these format standards in some way with a pre-commit hook, or some supportive tooling.
> Fix formatting inconsistencies in the code using buildifier

- csharp/BUILD
- csharp/defs.bzl
- csharp/private/BUILD
- csharp/private/actions/BUILD
- csharp/private/actions/assembly.bzl
- csharp/private/common.bzl
- csharp/private/macros/BUILD
- csharp/private/macros/setup_basic_nuget_package.bzl
- csharp/private/net/BUILD
- csharp/private/repositories.bzl
- csharp/private/rules/BUILD
- csharp/private/rules/binary.bzl
- csharp/private/rules/imports.bzl
- csharp/private/rules/library.bzl
- csharp/private/rules/library_set.bzl
- csharp/private/rules/nunit_test.bzl
- csharp/private/rules/wrapper.bzl
Aggregate all of the bazel sources together as using the model of `bzl_srcs`. This allows us to configure docs or tools on the bazel rule themselves. The top level is not accessible to any packages (e.g. `//docs`), as that will be handled in #110.
This PR aggregates all of the bazel sources to the top level using filegroups and the `bzl_srcs` model. This allows us to run tooling against our bazel rules files.
Relates to #17
> Aggregate the bazel rules files for use in tooling

- .bazelci/presubmit.yml
- csharp/defs.bzl
- csharp/private/BUILD
- csharp/private/actions/assembly.bzl
- csharp/private/common.bzl
- csharp/private/macros/nuget.bzl
- csharp/private/macros/setup_basic_nuget_package.bzl
- csharp/private/net/BUILD
- csharp/private/providers.bzl
- csharp/private/repositories.bzl
- csharp/private/rules/binary.bzl
- csharp/private/rules/imports.bzl
- csharp/private/rules/library.bzl
- csharp/private/rules/library_set.bzl
- csharp/private/rules/nunit_test.bzl
- csharp/private/rules/wrapper.bzl
- csharp/private/sdk.bzl
- csharp/private/toolchains.bzl
Requires that all WORKSPACE, BUILD, and .bzl files meet lint + formatting rules of buildifier. This is pinned to the latest version.
You can see the documentation for this [here](https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md#running-buildifier-on-ci).
Relates to #101, #111 
Additionally I performed a format of the YAML file, but there isn't any format guideline set in the code like `.clang-format`.
> Run buildifier in CI to keep formatting

- csharp/defs.bzl
- csharp/defs.for_docs.bzl
- csharp/private/actions/assembly.bzl
- csharp/private/common.bzl
- csharp/private/macros/nuget.bzl
- csharp/private/macros/setup_basic_nuget_package.bzl
- csharp/private/repositories.bzl
- csharp/private/rules/binary.bzl
- csharp/private/rules/imports.bzl
- csharp/private/rules/library.bzl
- csharp/private/rules/library_set.bzl
- csharp/private/rules/nunit_test.bzl
- csharp/private/rules/wrapper.bzl
- csharp/private/sdk.bzl
- csharp/private/toolchains.bzl
Configure docstrings for all of the rules files. The descriptions used for now are simple, but intended to roughly classify what the rule handles.
I expect these will become more verbose as the documentation of the rules are expanded/revised with each issue.
> Set the module docstrings for all rules

- csharp/private/BUILD
> All top level calls (except for some built-ins) should use keyword args over positional arguments. Positional arguments can cause subtle errors if the order is switched or if an argument is removed. Keyword args also greatly improve readability.
This PR resolves instances of the warning `positional-args` in the repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/brightspace/rules_csharp/114)
> buildifier - Resolve 'positional-args' warnings

- csharp/private/BUILD
- csharp/private/actions/assembly.bzl
- csharp/private/actions/write_runtimeconfig.bzl
- csharp/private/common.bzl
- csharp/private/providers.bzl
- csharp/private/rules/binary.bzl
- csharp/private/runtimeconfig.json.tpl
- csharp/private/sdk.bzl
- docs/APIReference.md
- examples/basic/BUILD
This is half of #71. The other half is invoking the exe with `dotnet` rather than directly (I'm going to use the wrapper to do this, but in a follow-up PR).
> Add runtimeconfig.json for .NET Core executables

- .bazelci/presubmit.yml
Upgrade bazel to the latest version in CI.
The full release announcement can be found in the [Blog entry on Bazel 2.0](https://blog.bazel.build/2019/12/19/bazel-2.0.html), and the release notes [here](https://github.com/bazelbuild/bazel/releases/tag/2.0.0).
> Upgrade to Bazel 2.0.0 in CI

- csharp/private/net/BUILD
The net workspace used for the framework dependencies is accessing a rule using an internal reference rather than using the public API.
This PR resolves the import to use the public API, rather than access private rules of rules_csharp.
This resolves the buildifier warning `bzl-visibility`
> Use public API instead of visibility to private

- csharp/private/actions/wrapper.bzl
- csharp/private/rules/wrapper.bzl
- csharp/private/wrappers/dotnet.cc
`csharp_binary` needs to become a rule which emits a `cc_binary` that
invokes `dotnet <foo>`, where `<foo>` is the actual dll that we
compile, to solve #71. Eventually `<foo>` will become a wrapper C# exe
that tweaks assembly loading to solve #9. So all of this requires the
wrapper to provide a default `argv[1]`.
For stuff like `dotnet vstest` (#51) we will have `argv[1]` be `vstest`, so we
also need support for baking in `argv[2]`.
> Generalize the dotnet wrapper a bit

- csharp/private/actions/assembly.bzl
In AssemblyAction, when adding arguments for the compiler command line, the [`args.add_all()`](https://docs.bazel.build/versions/master/skylark/lib/Args.html#add_all) call is looping through the `srcs` attribute, and adding the `.path` from each one. Since each element of the `srcs` attribute is a [File object](https://docs.bazel.build/versions/master/skylark/lib/File.html), adding the file names by calling `.path` is redundant; at rule execution time, the path is resolved and used as the string argument.
The motivation for this change is that `.add_all()` also understands File objects that are created with [`declare_directory()`](https://docs.bazel.build/versions/master/skylark/lib/actions.html#declare_directory), meaning a rule invoking a source code generator can be used, and the …
> Remove reliance on path attribute for srcs arguments

- csharp/private/actions/assembly.bzl
- csharp/private/actions/misc.bzl
- csharp/private/rules/binary_private.bzl
- csharp/private/rules/library.bzl
Also standardize on internals_visible_to rather than internalsvisibleto.
Part of #150
> Only wire up the internalsvisibleto codegen once rather than per-framework
